config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :categories
  resources :resources
  resources :technologies
  root 'technologies#index'

  devise_for :users

end

app/models/technology.rb
class Technology < ApplicationRecord
    has_many :categories
    has_many :resources, through: :categories
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :set_technology, only: [:show, :edit, :update, :destroy]

  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.all
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(technology_params)

    respond_to do |format|
      if @technology.save
        format.html { redirect_to @technology, notice: 'Technology was successfully created.' }
        format.json { render :show, status: :created, location: @technology }
      else
        format.html { render :new }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technologies/1
  # PATCH/PUT /technologies/1.json
  def update
    respond_to do |format|
      if @technology.update(technology_params)
        format.html { redirect_to @technology, notice: 'Technology was successfully updated.' }
        format.json { render :show, status: :ok, location: @technology }
      else
        format.html { render :edit }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology.destroy
    respond_to do |format|
      format.html { redirect_to technologies_url, notice: 'Technology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def technology_params
      params.require(:technology).permit(:name, :description)
    end
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/technologies/_form.html.erb
<%= form_with(model: technology, local: true) do |form| %>
  <% if technology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

      <ul>
        <% technology.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="actions">
    <%= form.text_field :name %>
    <%= form.text_field :description %>
    <%= form.submit %>
  </div>
<% end %>

app/views/technologies/_technology.html.erb
<div class="generic--card">
  <h2 class="technology--title"><%= link_to technology.name, technology %><h2>
</div>

<% if current_user %>

<ul>
  <li><%= link_to 'Show', technology %></li>
  <li><%= link_to 'Edit', edit_technology_path(technology) %></li>
  <li><%= link_to 'Destroy', technology, method: :delete, data: { confirm: 'Are you sure?' } %></li>
</ul>

<% end %>

app/views/technologies/edit.html.erb
<h1>Editing Technology</h1>

<%= render 'form', technology: @technology %>

<%= link_to 'Show', @technology %> |
<%= link_to 'Back', technologies_path %>

app/views/technologies/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_user %>
    <%=current_user.email%>
    <%= link_to "Logout", destroy_user_session_path, :method => :delete, :data => { :no_turbolink => true } %>
<% else %>
    <%= link_to "Sign In", new_user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path %>
<% end %> 
<h1 class="generic--title">Technologies</h1>
<div class="generic--search"> <input type="text"></div>

<%= link_to 'New Technology', new_technology_path %>

<div class="generic--grid">
  <% @technologies.each do |technology| %>
    <%= render technology %>
  <% end %>
</div>

app/views/technologies/new.html.erb
<h1>New Technology</h1>

<%= render 'form', technology: @technology %>

<%= link_to 'Back', technologies_path %>

app/views/technologies/show.html.erb
<p id="notice"><%= notice %></p>


<h1 class="generic--title">Categories</h1>
<div class="generic--search"> <input type="text"></div>

<div class="generic--grid">
  <% @technology.categories.each do |category| %>
  <p>Technology: <%=category.technology.name%> </p>

    <%= render category %>
  <% end %>
</div>

<%= link_to 'New Category', new_category_path %>